// Generated by gencpp from file rbc_2023/node2UI.msg
// DO NOT EDIT!


#ifndef RBC_2023_MESSAGE_NODE2UI_H
#define RBC_2023_MESSAGE_NODE2UI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbc_2023
{
template <class ContainerAllocator>
struct node2UI_
{
  typedef node2UI_<ContainerAllocator> Type;

  node2UI_()
    : mode(0)
    , data()
    , backStr()
    , rawStr()  {
    }
  node2UI_(const ContainerAllocator& _alloc)
    : mode(0)
    , data(_alloc)
    , backStr(_alloc)
    , rawStr(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _data_type;
  _data_type data;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _backStr_type;
  _backStr_type backStr;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _rawStr_type;
  _rawStr_type rawStr;





  typedef boost::shared_ptr< ::rbc_2023::node2UI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbc_2023::node2UI_<ContainerAllocator> const> ConstPtr;

}; // struct node2UI_

typedef ::rbc_2023::node2UI_<std::allocator<void> > node2UI;

typedef boost::shared_ptr< ::rbc_2023::node2UI > node2UIPtr;
typedef boost::shared_ptr< ::rbc_2023::node2UI const> node2UIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbc_2023::node2UI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbc_2023::node2UI_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbc_2023::node2UI_<ContainerAllocator1> & lhs, const ::rbc_2023::node2UI_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.data == rhs.data &&
    lhs.backStr == rhs.backStr &&
    lhs.rawStr == rhs.rawStr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbc_2023::node2UI_<ContainerAllocator1> & lhs, const ::rbc_2023::node2UI_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbc_2023

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rbc_2023::node2UI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbc_2023::node2UI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbc_2023::node2UI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbc_2023::node2UI_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbc_2023::node2UI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbc_2023::node2UI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbc_2023::node2UI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57e20d8a0746f7d6680c3406f4a78eb2";
  }

  static const char* value(const ::rbc_2023::node2UI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57e20d8a0746f7d6ULL;
  static const uint64_t static_value2 = 0x680c3406f4a78eb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbc_2023::node2UI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbc_2023/node2UI";
  }

  static const char* value(const ::rbc_2023::node2UI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbc_2023::node2UI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode\n"
"int32[] data\n"
"string backStr\n"
"string rawStr\n"
;
  }

  static const char* value(const ::rbc_2023::node2UI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbc_2023::node2UI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.data);
      stream.next(m.backStr);
      stream.next(m.rawStr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node2UI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbc_2023::node2UI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbc_2023::node2UI_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "backStr: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.backStr);
    s << indent << "rawStr: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.rawStr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBC_2023_MESSAGE_NODE2UI_H
