// Generated by gencpp from file rbc_2023/recive.msg
// DO NOT EDIT!


#ifndef RBC_2023_MESSAGE_RECIVE_H
#define RBC_2023_MESSAGE_RECIVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbc_2023
{
template <class ContainerAllocator>
struct recive_
{
  typedef recive_<ContainerAllocator> Type;

  recive_()
    : LaunchSpeed(0.0)  {
    }
  recive_(const ContainerAllocator& _alloc)
    : LaunchSpeed(0.0)  {
  (void)_alloc;
    }



   typedef double _LaunchSpeed_type;
  _LaunchSpeed_type LaunchSpeed;





  typedef boost::shared_ptr< ::rbc_2023::recive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbc_2023::recive_<ContainerAllocator> const> ConstPtr;

}; // struct recive_

typedef ::rbc_2023::recive_<std::allocator<void> > recive;

typedef boost::shared_ptr< ::rbc_2023::recive > recivePtr;
typedef boost::shared_ptr< ::rbc_2023::recive const> reciveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbc_2023::recive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbc_2023::recive_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbc_2023::recive_<ContainerAllocator1> & lhs, const ::rbc_2023::recive_<ContainerAllocator2> & rhs)
{
  return lhs.LaunchSpeed == rhs.LaunchSpeed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbc_2023::recive_<ContainerAllocator1> & lhs, const ::rbc_2023::recive_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbc_2023

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rbc_2023::recive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbc_2023::recive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbc_2023::recive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbc_2023::recive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbc_2023::recive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbc_2023::recive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbc_2023::recive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad511b29776a364dc3562d699cb5c9b0";
  }

  static const char* value(const ::rbc_2023::recive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad511b29776a364dULL;
  static const uint64_t static_value2 = 0xc3562d699cb5c9b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbc_2023::recive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbc_2023/recive";
  }

  static const char* value(const ::rbc_2023::recive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbc_2023::recive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 LaunchSpeed\n"
;
  }

  static const char* value(const ::rbc_2023::recive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbc_2023::recive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.LaunchSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct recive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbc_2023::recive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbc_2023::recive_<ContainerAllocator>& v)
  {
    s << indent << "LaunchSpeed: ";
    Printer<double>::stream(s, indent + "  ", v.LaunchSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBC_2023_MESSAGE_RECIVE_H
